### ISSUE TITLE
Missing anker_plugin_network.dll

### ISSUE THREAD

**Issue by David-Maisonave** [ankermake/AnkerMake-Slicer#7]
This project is missing **anker_plugin_network.dll**, and/or a way to build anker_plugin_network.dll.

The program can't attached to a printer without this DLL.

Please add this DLL or source code to build this DLL to the project.

FYI: I did try to copy this DLL from a previous build, but it gives a run time error stating it's unable to load the plugin.

**Comment by bubnikv** [comment]
> This project is missing *anker_plugin_network.dll*, and/or a way to build
anker_plugin_network.dll.

Not the DLL, but the source code of the said DLL as mandated by the AGPL
license AnkerMake-slicer s licensed with. Don't be like Bambulab!

**Comment by David-Maisonave** [comment]
> Not the DLL, but the source code of the said DLL as mandated by the AGPL
license AnkerMake-slicer s licensed with. Don't be like Bambulab!

**Could you please give the questioner the benefit of the thought?**

It looks like someone failed to upload the source code for anker_plugin_network.  I did a keyword search for anker_plugin_network, and I found files referencing the following path:
**AnkerMake-Slicer\AnkerSlicer\src\ankerplugins\anker_plugin_network**

Put the above path does not exist on Github. See following snapshot:
<img width="412" alt="Missing__Anker_Plugin_Network_SourceCode" src="https://user-images.githubusercontent.com/47364845/229678197-7a42eb5d-944f-471a-aa8f-c11039f5e16f.png">

Also, most of the other plugins are included in the AnkerSlicer project file, but not anker_plugin_network.

If the source code is located somewhere else, can you please give details on the source code location, and how to build it?
Can you please build the latest code, and post the binaries for download.

Thank you

**Comment by bubnikv** [comment]
Network plugin source code is still missing.
https://github.com/ankermake/AnkerMake-Slicer/tree/main/AnkerSlicer/src/ankerplugins
